# Match pre release beta tags on release branches.
name: Pre-release

on:
  push:
    branches:
      - release*
    tags:
      # Matches 1.2b3 and 1.2.3b4
      - "[0-9]+.[0-9]+[ab]?[0-9+]"
      - "[0-9]+.[0-9]+.[0-9]+[ab]?[0-9+]"

jobs:
  pre-release:
    runs-on: ubuntu-latest
    name: Build pre-release package

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@master
        name: Setup Python 3.8
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python -m pip install -U poetry

      - name: Build package
        run: poetry build
